import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, Download, Edit3, Loader2, RefreshCw, Search, ShieldAlert, Users } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { exportToExcel } from '@/lib/exportExcel';

const MASTER_ISSUES = ['missing_phone','invalid_phone','branch_needs_review','placeholder_customer_name','customer_name_contains_operational_data','duplicate_valid_phone'] as const;
type MasterIssue = (typeof MASTER_ISSUES)[number];
type Health = { checked_at:string|null; canonical_customers:number; merged_customers:number; complete_customers:number; warning_customers:number; critical_customers:number; missing_phone:number; invalid_phone:number; branch_needs_review:number; noisy_names:number; pending_reviews:number; unlinked_invoices:number; unlinked_followups:number };
type ReviewRow = { id:string; customer_id:string|null; customer_code:string|null; issue_type:MasterIssue; severity:string; current_value:Record<string,unknown>|null; suggested_value:Record<string,unknown>|null; created_at:string|null };
type CustomerEdit = { id:string; name:string; phone:string; branch:string; address:string; area:string };

const issueLabels: Record<MasterIssue,string> = {
  missing_phone:'الهاتف غير موجود', invalid_phone:'الهاتف غير صالح', branch_needs_review:'الفرع يحتاج مراجعة', placeholder_customer_name:'اسم العميل غير حقيقي', customer_name_contains_operational_data:'الاسم يحتوي بيانات تشغيلية', duplicate_valid_phone:'هاتف مشترك بين أكثر من عميل',
};
const issueStyles: Record<MasterIssue,string> = {
  missing_phone:'border-amber-200 bg-amber-50 text-amber-800', invalid_phone:'border-red-200 bg-red-50 text-red-800', branch_needs_review:'border-blue-200 bg-blue-50 text-blue-800', placeholder_customer_name:'border-red-200 bg-red-50 text-red-800', customer_name_contains_operational_data:'border-violet-200 bg-violet-50 text-violet-800', duplicate_valid_phone:'border-rose-300 bg-rose-50 text-rose-900',
};
function text(value:unknown,fallback='—'){const result=value==null?'':String(value).trim();return result||fallback;}
function current(row:ReviewRow,key:string){return text(row.current_value?.[key],'');}
function suggested(row:ReviewRow,key:string){return text(row.suggested_value?.[key],'');}
function Card({title,value,icon,note}:{title:string;value:number;icon:React.ReactNode;note?:string}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-500">{title}</p><p className="mt-2 text-3xl font-black">{Number(value||0).toLocaleString('ar-EG')}</p>{note&&<p className="mt-2 text-xs font-bold text-slate-500">{note}</p>}</div><div className="rounded-2xl bg-slate-100 p-3 text-slate-700">{icon}</div></div></div>}

export default function CustomerMasterQualityCenter(){
  const [health,setHealth]=useState<Health|null>(null); const [rows,setRows]=useState<ReviewRow[]>([]); const [count,setCount]=useState(0); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [exporting,setExporting]=useState(false); const [search,setSearch]=useState(''); const [issue,setIssue]=useState<'all'|MasterIssue>('all'); const [page,setPage]=useState(0); const [edit,setEdit]=useState<CustomerEdit|null>(null); const pageSize=50;
  const load=useCallback(async()=>{setLoading(true);try{const from=page*pageSize;let query=supabase.from('customer_data_review_queue').select('id,customer_id,customer_code,issue_type,severity,current_value,suggested_value,created_at',{count:'exact'}).eq('status','pending').in('issue_type',[...MASTER_ISSUES]).order('created_at',{ascending:true}).range(from,from+pageSize-1);if(issue!=='all')query=query.eq('issue_type',issue);if(search.trim()){const q=search.trim().replace(/[%_,]/g,'');query=query.or(`customer_code.ilike.%${q}%,current_value->>name.ilike.%${q}%,current_value->>customer_name.ilike.%${q}%,current_value->>phone.ilike.%${q}%,current_value->>customer_phone.ilike.%${q}%`)}const [h,r]=await Promise.all([supabase.from('dawaa_customer_data_health_center_v2').select('*').single(),query]);if(h.error)throw h.error;if(r.error)throw r.error;setHealth(h.data as Health);setRows((r.data||[]) as ReviewRow[]);setCount(r.count||0)}catch(error){toast.error(error instanceof Error?error.message:'تعذر تحميل مركز جودة العملاء')}finally{setLoading(false)}},[issue,page,search]);
  useEffect(()=>{void load()},[load]); useEffect(()=>setPage(0),[issue,search]); const pages=Math.max(1,Math.ceil(count/pageSize)); const issueCounts=useMemo(()=>({phone:Number(health?.missing_phone||0)+Number(health?.invalid_phone||0),branch:Number(health?.branch_needs_review||0),names:Number(health?.noisy_names||0)+Number(health?.critical_customers||0)}),[health]);
  const openEditor=async(row:ReviewRow)=>{if(!row.customer_id)return toast.error('الحالة غير مربوطة بملف عميل');const{data,error}=await supabase.from('customers').select('id,display_name,name,customer_name,normalized_phone,phone,customer_phone,mobile,effective_branch,corrected_branch,branch,branch_name,address,area').eq('id',row.customer_id).single();if(error)return toast.error(error.message);setEdit({id:data.id,name:text(data.display_name||data.name||data.customer_name,''),phone:text(data.normalized_phone||data.phone||data.customer_phone||data.mobile,''),branch:text(data.effective_branch||data.corrected_branch||data.branch||data.branch_name,''),address:text(data.address,''),area:text(data.area,'')})};
  const saveEdit=async()=>{if(!edit)return;if(!edit.name.trim())return toast.error('اسم العميل مطلوب');setSaving(true);try{const{error}=await supabase.rpc('update_customer_master_data_safe',{p_customer_id:edit.id,p_name:edit.name.trim()||null,p_phone:edit.phone.trim()||null,p_branch:edit.branch.trim()||null,p_address:edit.address.trim()||null,p_area:edit.area.trim()||null,p_reason:'customer_data_quality_center'});if(error)throw error;toast.success('تم تحديث العميل وتسجيل التغيير');setEdit(null);window.dispatchEvent(new CustomEvent('customer-data-changed'));await load()}catch(error){toast.error(error instanceof Error?error.message:'تعذر حفظ التصحيح')}finally{setSaving(false)}};
  const exportRows=async()=>{setExporting(true);try{const all:ReviewRow[]=[];for(let offset=0;;offset+=1000){let query=supabase.from('customer_data_review_queue').select('id,customer_id,customer_code,issue_type,severity,current_value,suggested_value,created_at').eq('status','pending').in('issue_type',[...MASTER_ISSUES]).order('created_at',{ascending:true}).range(offset,offset+999);if(issue!=='all')query=query.eq('issue_type',issue);const{data,error}=await query;if(error)throw error;const part=(data||[]) as ReviewRow[];all.push(...part);if(part.length<1000)break}if(!all.length)return toast.info('لا توجد حالات للتصدير');await exportToExcel(all.map(row=>({'معرف المراجعة':row.id,'معرف العميل':row.customer_id||'','كود العميل':row.customer_code||'','نوع المشكلة':issueLabels[row.issue_type],'الخطورة':row.severity,'الاسم الحالي':current(row,'name')||current(row,'customer_name'),'الهاتف الحالي':current(row,'phone')||current(row,'customer_phone')||current(row,'mobile'),'الفرع الحالي':current(row,'corrected_branch')||current(row,'branch'),'الاسم المقترح':suggested(row,'display_name'),'الهاتف الموحد':suggested(row,'normalized_phone'),'الفرع الفعلي':suggested(row,'effective_branch'),'الاسم المصحح':'','الهاتف المصحح':'','الفرع المصحح':'','العنوان المصحح':'','المنطقة المصححة':'','ملاحظات المراجعة':''})),`مركز_جودة_بيانات_العملاء_${new Date().toISOString().slice(0,10)}`,'حالات المراجعة');toast.success(`تم تصدير ${all.length.toLocaleString('ar-EG')} حالة`)}catch(error){toast.error(error instanceof Error?error.message:'تعذر التصدير')}finally{setExporting(false)}};
  return <section dir="rtl" className="space-y-5 rounded-[2rem] border border-slate-200 bg-slate-50 p-4 md:p-6"><div className="flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-indigo-50 p-3 text-indigo-700"><Database size={24}/></div><div><h2 className="text-xl font-black">مركز جودة ملف العملاء الرئيسي</h2><p className="mt-1 text-sm font-bold text-slate-500">تصحيح آمن مع سجل قبل وبعد التعديل، بدون دمج تلقائي بالاسم أو الهاتف.</p></div></div><p className="mt-3 text-xs font-bold text-slate-500">آخر فحص: {health?.checked_at?new Date(health.checked_at).toLocaleString('ar-EG'):'—'}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void exportRows()} disabled={exporting||loading} className="inline-flex items-center gap-2 rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{exporting?<Loader2 className="animate-spin" size={17}/>:<Download size={17}/>} تصدير كل النتائج</button><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black disabled:opacity-50"><RefreshCw className={loading?'animate-spin':''} size={17}/> تحديث</button></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card title="ملفات مكتملة" value={health?.complete_customers||0} icon={<CheckCircle2 size={21}/>}/><Card title="تحتاج مراجعة" value={health?.warning_customers||0} icon={<AlertTriangle size={21}/>} note={`${issueCounts.phone.toLocaleString('ar-EG')} مشكلة هاتف`}/><Card title="حالات حرجة" value={health?.critical_customers||0} icon={<ShieldAlert size={21}/>}/><Card title="عملاء فعليون" value={health?.canonical_customers||0} icon={<Users size={21}/>} note={`${Number(health?.merged_customers||0).toLocaleString('ar-EG')} مدمج/مكرر`}/><Card title="فروع تحتاج مراجعة" value={issueCounts.branch} icon={<Database size={21}/>}/><Card title="أسماء تحتاج مراجعة" value={issueCounts.names} icon={<Edit3 size={21}/>}/><Card title="فواتير غير مربوطة" value={health?.unlinked_invoices||0} icon={<AlertTriangle size={21}/>}/><Card title="متابعات غير مربوطة" value={health?.unlinked_followups||0} icon={<AlertTriangle size={21}/>}</div>
  <div className="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالكود أو الاسم أو الهاتف" className="w-full rounded-2xl border border-slate-200 py-3 pr-11 pl-4 text-sm outline-none focus:border-indigo-500"/></label><select value={issue} onChange={e=>setIssue(e.target.value as 'all'|MasterIssue)} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-black"><option value="all">كل مشكلات الملف الرئيسي</option>{MASTER_ISSUES.map(key=><option key={key} value={key}>{issueLabels[key]}</option>)}</select></div>
  {loading?<div className="flex min-h-48 items-center justify-center rounded-3xl bg-white"><Loader2 className="animate-spin text-indigo-600" size={32}/></div>:rows.length===0?<div className="rounded-3xl bg-white p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={38}/><p className="mt-3 font-black">لا توجد نتائج مطابقة</p></div>:<div className="grid gap-4 xl:grid-cols-2">{rows.map(row=>{const duplicate=row.issue_type==='duplicate_valid_phone';const name=current(row,'name')||current(row,'customer_name')||suggested(row,'display_name')||'عميل بدون اسم';const phone=current(row,'phone')||current(row,'customer_phone')||current(row,'mobile')||suggested(row,'normalized_phone');const branch=current(row,'corrected_branch')||current(row,'branch')||suggested(row,'effective_branch');return <article key={row.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-500">كود: {text(row.customer_code)}</p><h3 className="mt-1 text-lg font-black">{name}</h3><p className="mt-1 text-xs font-bold text-slate-500">{text(phone,'بدون هاتف')} · {text(branch,'بدون فرع')}</p></div><span className={`rounded-full border px-3 py-1 text-xs font-black ${issueStyles[row.issue_type]}`}>{issueLabels[row.issue_type]}</span></div>{duplicate&&<div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-900">لا يتم الدمج تلقائيًا؛ الرقم قد يكون مشتركًا بين أسرة أو جهة. راجع الملفات والمبيعات أولًا.</div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void openEditor(row)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-black text-white"><Edit3 size={15}/> تصحيح ملف العميل</button>{row.customer_id&&<a href={`/customers/${encodeURIComponent(row.customer_id)}`} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black">فتح ملف 360</a>}</div></article>})}</div>}
  <div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black"><span>{count.toLocaleString('ar-EG')} حالة · صفحة {(page+1).toLocaleString('ar-EG')} من {pages.toLocaleString('ar-EG')}</span><div className="flex gap-2"><button disabled={page===0} onClick={()=>setPage(v=>Math.max(0,v-1))} className="rounded-xl border px-3 py-2 disabled:opacity-40">السابق</button><button disabled={page+1>=pages} onClick={()=>setPage(v=>v+1)} className="rounded-xl border px-3 py-2 disabled:opacity-40">التالي</button></div></div>
  {edit&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-black">تصحيح ملف العميل</h3><p className="mt-1 text-sm font-bold text-slate-500">سيتم تسجيل القيمة قبل وبعد التعديل.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">الاسم<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-black">الهاتف<input value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-black">الفرع<input value={edit.branch} onChange={e=>setEdit({...edit,branch:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-black">المنطقة<input value={edit.area} onChange={e=>setEdit({...edit,area:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-black sm:col-span-2">العنوان<input value={edit.address} onChange={e=>setEdit({...edit,address:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setEdit(null)} disabled={saving} className="rounded-xl border px-5 py-3 text-sm font-black">إلغاء</button><button onClick={()=>void saveEdit()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving&&<Loader2 className="animate-spin" size={16}/>} حفظ واعتماد التصحيح</button></div></div></div>}</section>
}
