import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, History, LockKeyhole, RefreshCw, Scale, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/hooks/useAuth';
import { buildGovernanceCsv, fetchIncentiveCycleDetails, fetchIncentiveGovernance, transitionIncentiveCycle, type IncentiveAudit, type IncentiveCycle, type IncentiveRisk, type IncentiveSnapshot } from '@/lib/incentives/incentiveGovernanceService';

const statusLabel:Record<string,string>={open:'مفتوحة',preview:'معاينة',manager_review:'مراجعة الإدارة',finance_review:'مراجعة المالية',approved:'اعتماد نهائي',paid:'تم الصرف',reopened:'معاد فتحها'};
const money=(n:number)=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n);
const date=(v:string)=>new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:v.includes('T')?'short':undefined,timeZone:'Africa/Cairo'}).format(new Date(v));
const card=(label:string,value:string,tone:string)=><div className={`rounded-2xl border p-4 ${tone}`}><p className="text-xs font-bold opacity-75">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>;

export default function IncentiveGovernance(){
  const { user }=useAuth(); const [cycles,setCycles]=useState<IncentiveCycle[]>([]); const [cycleId,setCycleId]=useState('');
  const [rows,setRows]=useState<IncentiveSnapshot[]>([]); const [risks,setRisks]=useState<IncentiveRisk[]>([]); const [audit,setAudit]=useState<IncentiveAudit[]>([]);
  const [appeals,setAppeals]=useState(0); const [loading,setLoading]=useState(true); const [history,setHistory]=useState<3|6|12>(3);
  const loadCycles=async()=>{const result=await fetchIncentiveGovernance();setCycles(result.cycles);setCycleId(v=>v||result.cycles[0]?.id||'');};
  const loadDetails=async(id:string)=>{if(!id)return;setLoading(true);try{const d=await fetchIncentiveCycleDetails(id);setRows(d.snapshots);setRisks(d.risks);setAudit(d.audit);setAppeals(d.appeals.filter(a=>['submitted','under_review'].includes(a.status)).length);}catch(e){toast.error(e instanceof Error?e.message:'تعذر تحميل الحوافز');}finally{setLoading(false);}};
  useEffect(()=>{loadCycles().catch(e=>{toast.error(e.message);setLoading(false);});},[]); useEffect(()=>{loadDetails(cycleId);},[cycleId]);
  const cycle=cycles.find(c=>c.id===cycleId); const sums=useMemo(()=>rows.reduce((a,r)=>({performance:a.performance+r.performanceIncentive,target:a.target+r.targetBonus,other:a.other+r.otherIncentives,deductions:a.deductions+r.deductions,total:a.total+r.totalIncentive,eligible:a.eligible+(r.eligible?1:0)}),{performance:0,target:0,other:0,deductions:0,total:0,eligible:0}),[rows]);
  const transition=async(next:any)=>{if(!cycle||!user)return;let reason:string|undefined;if(next==='reopened'){reason=window.prompt('اكتب سبب إعادة الفتح بوضوح (10 أحرف على الأقل)')||undefined;if(!reason||reason.trim().length<10)return toast.error('سبب إعادة الفتح إلزامي وواضح');}try{await transitionIncentiveCycle(cycle.id,next,{id:user.id,name:user.name},reason);toast.success('تم تسجيل مرحلة الاعتماد');await loadCycles();await loadDetails(cycle.id);}catch(e){toast.error(e instanceof Error?e.message:'تعذر تنفيذ الاعتماد');}};
  const exportCsv=()=>{const blob=new Blob([buildGovernanceCsv(rows)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`incentive-governance-${cycle?.cycleStart||'cycle'}.csv`;a.click();URL.revokeObjectURL(url);};
  const next=cycle?.status==='manager_review'?'finance_review':cycle?.status==='finance_review'?'approved':cycle?.status==='approved'?'paid':cycle?.status==='reopened'?'manager_review':null;
  return <main dir="rtl" className="space-y-6 pb-10 text-slate-100">
    <section className="rounded-3xl border border-teal-400/20 bg-gradient-to-l from-slate-950 to-slate-900 p-5 shadow-xl"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-teal-300"><ShieldCheck/><span className="text-sm font-black">حوكمة مالية موثقة</span></div><h1 className="mt-2 text-3xl font-black text-white">اعتماد الحوافز</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-300">فصل كامل بين حافز الأداء وحافز التارجت، مع منع الصرف قبل اكتمال الدورة والبيانات والاعتراضات.</p></div><div className="flex flex-wrap gap-2"><select aria-label="اختيار دورة الحوافز" value={cycleId} onChange={e=>setCycleId(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm">{cycles.map(c=><option key={c.id} value={c.id}>{date(c.cycleStart)} ← {date(c.cycleEnd)} — {statusLabel[c.status]}</option>)}</select><button onClick={()=>loadDetails(cycleId)} className="rounded-xl border border-slate-700 p-3"><RefreshCw size={18}/></button><button onClick={exportCsv} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-3 text-sm font-black"><Download size={18}/>تصدير CSV</button></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{card('حافز الأداء',money(sums.performance),'border-blue-400/20 bg-blue-500/10 text-blue-100')}{card('حافز التارجت',money(sums.target),'border-emerald-400/20 bg-emerald-500/10 text-emerald-100')}{card('حوافز أخرى',money(sums.other),'border-violet-400/20 bg-violet-500/10 text-violet-100')}{card('الخصومات',money(sums.deductions),'border-red-400/20 bg-red-500/10 text-red-100')}{card('إجمالي المستحق',money(sums.total),'border-teal-400/30 bg-teal-500/15 text-teal-50')}{card('مؤهل / مراجعة',`${sums.eligible} / ${rows.length-sums.eligible}`,'border-amber-400/20 bg-amber-500/10 text-amber-100')}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4"><div className="flex flex-wrap items-center gap-2">{['manager_review','finance_review','approved','paid'].map((s,i)=><div key={s} className={`rounded-full px-4 py-2 text-xs font-black ${cycle?.status===s?'bg-teal-500 text-slate-950':'bg-slate-800 text-slate-300'}`}>{i+1}. {statusLabel[s]}</div>)}<span className="mr-auto rounded-full bg-slate-950 px-4 py-2 text-xs">الحالة: {statusLabel[cycle?.status||'open']}</span></div>{(risks.length||appeals)?<div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-500/10 p-3 text-sm text-amber-100"><AlertTriangle className="ml-2 inline" size={17}/>موانع الاعتماد: {risks.length} — اعتراضات مفتوحة: {appeals}</div>:null}<div className="mt-4 flex gap-2">{next?<button onClick={()=>transition(next)} disabled={loading} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-black disabled:opacity-50"><CheckCircle2 className="ml-2 inline" size={17}/>الانتقال إلى {statusLabel[next]}</button>:null}{cycle&&['approved','paid'].includes(cycle.status)?<button onClick={()=>transition('reopened')} className="rounded-xl border border-amber-500/40 px-5 py-2.5 text-sm font-black text-amber-200"><LockKeyhole className="ml-2 inline" size={17}/>إعادة فتح موثقة</button>:null}</div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-4"><h2 className="text-lg font-black">التقرير الجماعي</h2></div><div className="overflow-x-auto"><table className="min-w-[1600px] w-full text-right text-xs"><thead className="bg-slate-950 text-slate-300"><tr>{['الموظف','الوظيفة','الفرع','درجة الأداء','الأسابيع','التغطية','حافز الأداء','التارجت','المبيعات','نسبة التارجت','حافز التارجت','أخرى','خصومات','الصافي','الأهلية والسبب'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-800/80 hover:bg-white/[.03]"><td className="p-3 font-bold text-white">{r.staffName}</td><td className="p-3">{r.role}</td><td className="p-3">{r.branch}</td><td className="p-3">{r.performanceScore??'غير متاح'}</td><td className="p-3">{r.approvedWeeks}</td><td className="p-3">{r.dataCoveragePercent==null?'غير متاح':`${r.dataCoveragePercent}%`}</td><td className="p-3 text-blue-300">{money(r.performanceIncentive)}</td><td className="p-3">{money(r.targetAmount)}</td><td className="p-3">{money(r.salesAmount)}</td><td className="p-3">{r.targetAchievementPercent==null?'غير متاح':`${r.targetAchievementPercent}%`}</td><td className="p-3 text-emerald-300">{money(r.targetBonus)}</td><td className="p-3">{money(r.otherIncentives)}</td><td className="p-3 text-red-300">{money(r.deductions)}</td><td className="p-3 font-black text-teal-300">{money(r.totalIncentive)}</td><td className="p-3"><span className={r.eligible?'text-emerald-300':'text-amber-300'}>{r.eligible?'مؤهل':r.eligibilityReasons.join('، ')||'يحتاج مراجعة'}</span></td></tr>)}</tbody></table>{!rows.length&&!loading?<p className="p-8 text-center text-slate-400">لا توجد لقطة معتمدة لهذه الدورة بعد.</p>:null}</div></section>
    <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Scale className="text-teal-300"/>قواعد الصرف</h2><ul className="mt-4 space-y-2 text-sm leading-7 text-slate-300"><li>• الأداء مستقل: 3 أسابيع معتمدة وتغطية آلية 80% على الأقل؛ المصدر المفقود يُستبعد ويُعاد توزيع وزنه.</li><li>• المدير: 100% = 1000 ج، من 90% لأقل من 100% = 750 ج.</li><li>• الدكتور: 100% = 600 ج، من 90% لأقل من 100% = 450 ج.</li><li>• خدمة العملاء لا تحصل على حافز تارجت تلقائيًا، والدورة المفتوحة لا تُسوّى.</li></ul></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-black"><History className="text-teal-300"/>سجل التدقيق والتاريخ</h2><select value={history} onChange={e=>setHistory(Number(e.target.value) as 3|6|12)} className="rounded-lg bg-slate-950 p-2 text-xs"><option value={3}>آخر 3 دورات</option><option value={6}>آخر 6 دورات</option><option value={12}>آخر 12 دورة</option></select></div><div className="mt-4 max-h-72 space-y-3 overflow-auto">{audit.map(a=><div key={a.id} className="rounded-xl bg-slate-950 p-3 text-xs"><p className="font-bold text-white">{a.actorName||'النظام'} — {a.action}</p><p className="mt-1 text-slate-400">{a.fromStatus&&`${statusLabel[a.fromStatus]} ← `}{a.toStatus&&statusLabel[a.toStatus]} · {date(a.createdAt)}</p>{a.reason?<p className="mt-1 text-amber-200">السبب: {a.reason}</p>:null}</div>)}</div><p className="mt-3 text-xs text-slate-500">اختيار {history} دورات يحدد نطاق تقرير الموظف التاريخي عند توفر اللقطات.</p></div></section>
  </main>;
}
