-- Intentionally no database wrapper.
-- Demand Evidence completeness is exposed through the staff-authenticated Edge Function
-- purchase-demand-evidence-completeness. The inner aggregate RPC remains unavailable to anon.
