create or replace function public.get_doctor_competition_support_v1(p_start date, p_end date, p_branch text default null)
returns table(source_type text,staff_id text,doctor_name text,branch text,item_count bigint,metric_total numeric,secondary_total numeric,tertiary_total numeric,excellent_count bigint,negative_count bigint,completed_count bigint,recovered_count bigint)
language sql stable security invoker set search_path = public as $$
with reviews as (
  select coalesce(r.staff_id::text,r.doctor_id::text,'') staff_id,coalesce(nullif(btrim(r.staff_name),''),nullif(btrim(r.doctor_name),''),'غير محدد') doctor_name,coalesce(nullif(btrim(r.branch),''),'غير محدد') branch,
    count(*) filter(where coalesce(r.final_score,0)>0)::bigint item_count,coalesce(sum(r.final_score) filter(where coalesce(r.final_score,0)>0),0)::numeric metric_total,0::numeric secondary_total,0::numeric tertiary_total,
    count(*) filter(where coalesce(r.final_score,0)>=90)::bigint excellent_count,count(*) filter(where coalesce(r.final_score,0)>0 and r.final_score<70)::bigint negative_count,0::bigint completed_count,0::bigint recovered_count
  from public.conversation_sales_reviews r where coalesce(r.conversation_date,r.created_at)>=p_start::timestamptz and coalesce(r.conversation_date,r.created_at)<(p_end+1)::timestamptz
    and (p_branch is null or btrim(p_branch)='' or p_branch in ('الكل','كل الفروع','all') or r.branch=p_branch) group by 1,2,3
), followups as (
  select coalesce(f.staff_id::text,'') staff_id,coalesce(nullif(btrim(f.responsible_name),''),nullif(btrim(f.assigned_doctor),''),nullif(btrim(f.assigned_to),''),nullif(btrim(f.created_by_name),''),'غير محدد') doctor_name,coalesce(nullif(btrim(f.branch),''),'غير محدد') branch,
    count(*)::bigint item_count,coalesce(sum(coalesce(f.purchase_amount,0)) filter(where coalesce(f.purchase_after_followup,false)),0)::numeric metric_total,
    coalesce(sum(case when nullif(regexp_replace(coalesce(f.customer_satisfaction,''),'[^0-9.]','','g'),'') is not null then nullif(regexp_replace(coalesce(f.customer_satisfaction,''),'[^0-9.]','','g'),'')::numeric when coalesce(f.quality_rating,0)>0 then f.quality_rating::numeric else 0 end),0)::numeric secondary_total,
    count(*) filter(where nullif(regexp_replace(coalesce(f.customer_satisfaction,''),'[^0-9.]','','g'),'') is not null or coalesce(f.quality_rating,0)>0)::numeric tertiary_total,0::bigint excellent_count,0::bigint negative_count,
    count(*) filter(where f.cancelled_at is null and f.archived_at is null and f.hidden_at is null and coalesce(f.is_hidden,false)=false and (lower(btrim(coalesce(f.status,''))) in ('completed','closed','done','تم','مكتمل','تم الشراء بعد المتابعة') or lower(btrim(coalesce(f.followup_status,''))) in ('completed','closed','done','تم','مكتمل','تم الشراء بعد المتابعة') or (lower(btrim(coalesce(f.followup_result,f.contact_result,''))) not in ('','لم تبدأ','جارٍ التواصل','تمت محاولة','موعد قادم','تحتاج مديرًا','تم الرد ويحتاج طلب','تم الرد ويوجد شكوى','طلب صنف','طلب توصيل','يحتاج متابعة مدير','لم يرد','طلب التواصل لاحقًا','الرقم غير صحيح','مؤجل','معلق','pending','open','not_started','in_progress','attempted','scheduled','needs_manager','postponed','no_answer','no answer','contacted','responded') and (f.completed_at is not null or f.closed_at is not null or lower(btrim(coalesce(f.followup_result,f.contact_result,''))) in ('تم الرد والعميل راضي','تم الرد ولا يحتاج الآن','تم الشراء بعد المتابعة','تم حل الشكوى','تم تنفيذ الطلب والتأكد من العميل','completed','closed','done')))))::bigint completed_count,
    count(*) filter(where coalesce(f.purchase_after_followup,false))::bigint recovered_count
  from public.daily_followups f where f.created_at>=p_start::timestamptz and f.created_at<(p_end+1)::timestamptz and (p_branch is null or btrim(p_branch)='' or p_branch in ('الكل','كل الفروع','all') or f.branch=p_branch) group by 1,2,3
), stagnant as (
  select coalesce(d.doctor_id::text,'') staff_id,coalesce(nullif(btrim(d.doctor_name),''),'غير محدد') doctor_name,coalesce(nullif(btrim(d.branch_name),''),'غير محدد') branch,count(*)::bigint item_count,coalesce(sum(d.quantity),0)::numeric metric_total,coalesce(sum(d.total_incentive),0)::numeric secondary_total,0::numeric tertiary_total,0::bigint excellent_count,0::bigint negative_count,0::bigint completed_count,0::bigint recovered_count
  from public.stagnant_medicine_dispenses d where coalesce(d.dispensed_at,d.created_at)>=p_start::timestamptz and coalesce(d.dispensed_at,d.created_at)<(p_end+1)::timestamptz and (p_branch is null or btrim(p_branch)='' or p_branch in ('الكل','كل الفروع','all') or d.branch_name=p_branch) group by 1,2,3
), incentives as (
  select coalesce(s.doctor_id,'') staff_id,coalesce(nullif(btrim(s.doctor_name),''),'غير محدد') doctor_name,coalesce(nullif(btrim(s.branch),''),'غير محدد') branch,count(*)::bigint item_count,coalesce(sum(s.quantity),0)::numeric metric_total,coalesce(sum(s.incentive_total),0)::numeric secondary_total,0::numeric tertiary_total,0::bigint excellent_count,0::bigint negative_count,0::bigint completed_count,0::bigint recovered_count
  from public.incentive_medicine_sales s where coalesce(s.sale_date,s.created_at::date) between p_start and p_end and (p_branch is null or btrim(p_branch)='' or p_branch in ('الكل','كل الفروع','all') or s.branch=p_branch) group by 1,2,3
)
select 'reviews'::text,r.staff_id,r.doctor_name,r.branch,r.item_count,r.metric_total,r.secondary_total,r.tertiary_total,r.excellent_count,r.negative_count,r.completed_count,r.recovered_count from reviews r
union all select 'followups',f.staff_id,f.doctor_name,f.branch,f.item_count,f.metric_total,f.secondary_total,f.tertiary_total,f.excellent_count,f.negative_count,f.completed_count,f.recovered_count from followups f
union all select 'stagnant',s.staff_id,s.doctor_name,s.branch,s.item_count,s.metric_total,s.secondary_total,s.tertiary_total,s.excellent_count,s.negative_count,s.completed_count,s.recovered_count from stagnant s
union all select 'incentive',i.staff_id,i.doctor_name,i.branch,i.item_count,i.metric_total,i.secondary_total,i.tertiary_total,i.excellent_count,i.negative_count,i.completed_count,i.recovered_count from incentives i;
$$;
revoke all on function public.get_doctor_competition_support_v1(date,date,text) from public;
grant execute on function public.get_doctor_competition_support_v1(date,date,text) to authenticated;
