create table if not exists public.warehouse_shortage_dispatches (
  id uuid primary key default gen_random_uuid(),
  dispatch_no bigint generated by default as identity unique,
  branch text not null default 'all',
  generated_at timestamptz not null default now(),
  sent_at timestamptz not null default now(),
  total_products integer not null default 0,
  total_requests integer not null default 0,
  total_quantity numeric not null default 0,
  urgent_requests integer not null default 0,
  unlinked_products integer not null default 0,
  notes text null,
  created_by uuid null,
  created_by_label text null,
  created_at timestamptz not null default now()
);

create table if not exists public.warehouse_shortage_dispatch_items (
  id uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references public.warehouse_shortage_dispatches(id) on delete cascade,
  product_id uuid null references public.products(id) on delete set null,
  product_key text not null,
  product_code text null,
  product_name text not null,
  total_quantity numeric not null default 0,
  request_count integer not null default 0,
  customer_count integer not null default 0,
  urgent_count integer not null default 0,
  branch_breakdown jsonb not null default '{}'::jsonb,
  request_ids jsonb not null default '[]'::jsonb,
  request_names jsonb not null default '[]'::jsonb,
  link_quality text not null default 'unlinked',
  oldest_request_at timestamptz null,
  latest_request_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists idx_warehouse_shortage_dispatches_branch_sent
  on public.warehouse_shortage_dispatches(branch, sent_at desc);
create index if not exists idx_warehouse_shortage_dispatch_items_dispatch
  on public.warehouse_shortage_dispatch_items(dispatch_id);
create index if not exists idx_warehouse_shortage_dispatch_items_product_key
  on public.warehouse_shortage_dispatch_items(product_key, created_at desc);
create index if not exists idx_warehouse_shortage_dispatch_items_product_code
  on public.warehouse_shortage_dispatch_items(product_code) where product_code is not null;

alter table public.warehouse_shortage_dispatches enable row level security;
alter table public.warehouse_shortage_dispatch_items enable row level security;

revoke all on table public.warehouse_shortage_dispatches from anon, authenticated;
revoke all on table public.warehouse_shortage_dispatch_items from anon, authenticated;
grant select on table public.warehouse_shortage_dispatches to anon, authenticated;
grant select on table public.warehouse_shortage_dispatch_items to anon, authenticated;
grant all on table public.warehouse_shortage_dispatches to service_role;
grant all on table public.warehouse_shortage_dispatch_items to service_role;

drop policy if exists warehouse_shortage_dispatches_read on public.warehouse_shortage_dispatches;
create policy warehouse_shortage_dispatches_read on public.warehouse_shortage_dispatches
for select to anon, authenticated
using ((select auth.uid()) is not null or public.dawaa_has_active_app_session());

drop policy if exists warehouse_shortage_dispatch_items_read on public.warehouse_shortage_dispatch_items;
create policy warehouse_shortage_dispatch_items_read on public.warehouse_shortage_dispatch_items
for select to anon, authenticated
using ((select auth.uid()) is not null or public.dawaa_has_active_app_session());

create or replace function public.record_warehouse_shortage_dispatch(
  p_branch text,
  p_summary jsonb,
  p_items jsonb,
  p_notes text default null,
  p_created_by_label text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_dispatch_id uuid;
  v_dispatch_no bigint;
  v_item jsonb;
begin
  if not ((select auth.uid()) is not null or public.dawaa_has_active_app_session()) then
    raise exception 'not_authorized';
  end if;

  insert into public.warehouse_shortage_dispatches(
    branch,
    generated_at,
    sent_at,
    total_products,
    total_requests,
    total_quantity,
    urgent_requests,
    unlinked_products,
    notes,
    created_by,
    created_by_label
  ) values (
    coalesce(nullif(trim(p_branch), ''), 'all'),
    coalesce((p_summary->>'generated_at')::timestamptz, now()),
    now(),
    coalesce((p_summary->>'total_products')::integer, 0),
    coalesce((p_summary->>'total_requests')::integer, 0),
    coalesce((p_summary->>'total_quantity')::numeric, 0),
    coalesce((p_summary->>'urgent_requests')::integer, 0),
    coalesce((p_summary->>'unlinked_products')::integer, 0),
    nullif(trim(coalesce(p_notes, '')), ''),
    (select auth.uid()),
    nullif(trim(coalesce(p_created_by_label, '')), '')
  )
  returning id, dispatch_no into v_dispatch_id, v_dispatch_no;

  for v_item in select value from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    insert into public.warehouse_shortage_dispatch_items(
      dispatch_id,
      product_id,
      product_key,
      product_code,
      product_name,
      total_quantity,
      request_count,
      customer_count,
      urgent_count,
      branch_breakdown,
      request_ids,
      request_names,
      link_quality,
      oldest_request_at,
      latest_request_at
    ) values (
      v_dispatch_id,
      nullif(v_item->>'product_id', '')::uuid,
      coalesce(nullif(v_item->>'product_key', ''), 'unknown:' || v_dispatch_id::text),
      nullif(v_item->>'product_code', ''),
      coalesce(nullif(v_item->>'product_name', ''), 'صنف غير محدد'),
      coalesce((v_item->>'total_quantity')::numeric, 0),
      coalesce((v_item->>'request_count')::integer, 0),
      coalesce((v_item->>'customer_count')::integer, 0),
      coalesce((v_item->>'urgent_count')::integer, 0),
      coalesce(v_item->'branch_breakdown', '{}'::jsonb),
      coalesce(v_item->'request_ids', '[]'::jsonb),
      coalesce(v_item->'request_names', '[]'::jsonb),
      coalesce(nullif(v_item->>'link_quality', ''), 'unlinked'),
      nullif(v_item->>'oldest_request_at', '')::timestamptz,
      nullif(v_item->>'latest_request_at', '')::timestamptz
    );
  end loop;

  return jsonb_build_object(
    'id', v_dispatch_id,
    'dispatch_no', v_dispatch_no,
    'sent_at', now(),
    'items', jsonb_array_length(coalesce(p_items, '[]'::jsonb))
  );
end;
$$;

revoke execute on function public.record_warehouse_shortage_dispatch(text,jsonb,jsonb,text,text) from public;
revoke execute on function public.record_warehouse_shortage_dispatch(text,jsonb,jsonb,text,text) from anon, authenticated;
grant execute on function public.record_warehouse_shortage_dispatch(text,jsonb,jsonb,text,text) to anon, authenticated, service_role;
