-- Movement-aware, dosage-safe product matching for Base44 customer requests.

create table if not exists public.product_movement_evidence (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  product_code text not null,
  branch text,
  movement_date date not null,
  quantity numeric not null default 0,
  movement_type text not null default 'sale',
  source text not null default 'manual_import',
  source_ref text,
  created_at timestamptz not null default now()
);

create index if not exists idx_product_movement_evidence_product_date on public.product_movement_evidence(product_id, movement_date desc);
create index if not exists idx_product_movement_evidence_code_date on public.product_movement_evidence(product_code, movement_date desc);

create or replace function public.customer_request_smart_product_text_v2(p_value text)
returns text
language plpgsql
immutable
set search_path=public,pg_catalog
as $$
declare v text := lower(coalesce(p_value,''));
begin
  v := translate(v, 'أإآىةؤئ', 'ااايهوي');
  v := regexp_replace(v, '[\u064B-\u065F\u0670]', '', 'g');
  v := replace(v, 'milligrams', ' mg '); v := replace(v, 'milligram', ' mg ');
  v := replace(v, 'مجم', ' mg '); v := replace(v, 'مغ', ' mg ');
  v := replace(v, 'micrograms', ' mcg '); v := replace(v, 'microgram', ' mcg ');
  v := replace(v, 'milliliters', ' ml '); v := replace(v, 'milliliter', ' ml ');
  v := replace(v, 'مللي', ' ml '); v := replace(v, 'مللى', ' ml ');
  v := replace(v, 'tablets', ' tab '); v := replace(v, 'tablet', ' tab ');
  v := replace(v, 'اقراص', ' tab '); v := replace(v, 'قرص', ' tab ');
  v := replace(v, 'capsules', ' cap '); v := replace(v, 'capsule', ' cap ');
  v := replace(v, 'كبسولات', ' cap '); v := replace(v, 'كبسوله', ' cap ');
  v := replace(v, 'ampoules', ' amp '); v := replace(v, 'ampoule', ' amp ');
  v := replace(v, 'امبولات', ' amp '); v := replace(v, 'امبول', ' amp ');
  v := regexp_replace(v, '([0-9])([a-z\u0600-\u06ff])', '\1 \2', 'g');
  v := regexp_replace(v, '([a-z\u0600-\u06ff])([0-9])', '\1 \2', 'g');
  v := regexp_replace(v, '[^a-z0-9\u0600-\u06ff.%]+', ' ', 'g');
  v := regexp_replace(v, '\s+', ' ', 'g');
  return nullif(trim(v),'');
end;
$$;

create or replace function public.customer_request_strength_tokens_v2(p_value text)
returns text[]
language sql
immutable
set search_path=public,pg_catalog
as $$
  with x as (select public.customer_request_smart_product_text_v2(p_value) v),
  m as (
    select lower(replace(r[1],' ','')) token
    from x, regexp_matches(coalesce(v,''), '([0-9]+(?:[.]?[0-9]+)?\s*(?:mg|mcg|g|ml|iu|%))', 'g') r
  )
  select coalesce(array_agg(distinct token order by token), array[]::text[]) from m;
$$;

create or replace function public.customer_request_form_v2(p_value text)
returns text
language sql
immutable
set search_path=public,pg_catalog
as $$
  select case
    when coalesce(public.customer_request_smart_product_text_v2(p_value),'') ~ '(^| )(amp|امبوله)( |$)' then 'amp'
    when coalesce(public.customer_request_smart_product_text_v2(p_value),'') ~ '(^| )(tab)( |$)' then 'tab'
    when coalesce(public.customer_request_smart_product_text_v2(p_value),'') ~ '(^| )(cap)( |$)' then 'cap'
    when lower(coalesce(p_value,'')) ~ '(cream|كريم)' then 'cream'
    when lower(coalesce(p_value,'')) ~ '(gel|جل)' then 'gel'
    when lower(coalesce(p_value,'')) ~ '(syrup|syp|شراب)' then 'syrup'
    when lower(coalesce(p_value,'')) ~ '(spray|بخاخ|سبراي)' then 'spray'
    when lower(coalesce(p_value,'')) ~ '(drop|drops|قطره|قطرة)' then 'drop'
    when lower(coalesce(p_value,'')) ~ '(supp|suppos|لبوس|تحميل)' then 'supp'
    when lower(coalesce(p_value,'')) ~ '(sachet|sachets|كيس|اكياس)' then 'sachet'
    when lower(coalesce(p_value,'')) ~ '(lotion|لوشن)' then 'lotion'
    when lower(coalesce(p_value,'')) ~ '(ointment|oint|مرهم)' then 'ointment'
    else null end;
$$;

create index if not exists idx_products_smart_match_trgm_v2 on public.products using gin (public.customer_request_smart_product_text_v2(name) gin_trgm_ops);
create index if not exists idx_customer_requests_product_id_status_v2 on public.customer_requests(product_id,status) where product_id is not null;
create index if not exists idx_customer_requests_smart_name_linked_v2 on public.customer_requests(public.customer_request_smart_product_text_v2(medicine_name),product_id) where product_id is not null;

create or replace function public.get_customer_request_product_candidates_v2(p_request_id uuid,p_limit integer default 5)
returns table(
  product_id uuid, product_code text, product_name text, price numeric, match_score numeric,
  name_similarity numeric, alias_confirmations bigint, fulfilled_history bigint,
  movement_qty_180 numeric, movement_events_180 bigint, last_movement_date date,
  strength_match boolean, form_match boolean, blocked_reason text, confidence_label text
)
language sql stable security definer set search_path=public,pg_catalog as $$
with req as (
  select cr.id,cr.medicine_name,
         public.customer_request_smart_product_text_v2(cr.medicine_name) norm,
         public.customer_request_strength_tokens_v2(cr.medicine_name) strengths,
         public.customer_request_form_v2(cr.medicine_name) form
  from public.customer_requests cr where cr.id=p_request_id
), raw_candidates as (
  select p.*, public.customer_request_smart_product_text_v2(p.name) pnorm,
         public.customer_request_strength_tokens_v2(p.name) pstrengths,
         public.customer_request_form_v2(p.name) pform,
         similarity(r.norm, public.customer_request_smart_product_text_v2(p.name)) sim
  from req r
  join lateral (
    select px.* from public.products px
    where public.customer_request_smart_product_text_v2(px.name) % r.norm
    order by similarity(public.customer_request_smart_product_text_v2(px.name),r.norm) desc
    limit 20
  ) p on true
), hist as (
  select h.product_id,
    count(*) filter(where public.customer_request_smart_product_text_v2(h.medicine_name)=(select norm from req)) alias_count,
    count(*) filter(where h.status in ('available','arrived','customer_contacted','delivered','closed')) fulfilled_count
  from public.customer_requests h where h.product_id in (select id from raw_candidates) group by h.product_id
), moves as (
  select e.product_id,sum(abs(e.quantity)) filter(where e.movement_date>=current_date-180) move_qty,
    count(*) filter(where e.movement_date>=current_date-180) move_events,max(e.movement_date) last_move
  from public.product_movement_evidence e where e.product_id in (select id from raw_candidates) group by e.product_id
), enriched as (
  select c.*,coalesce(h.alias_count,0) alias_count,coalesce(h.fulfilled_count,0) fulfilled_count,
    coalesce(m.move_qty,0) move_qty,coalesce(m.move_events,0) move_events,m.last_move,
    ((select cardinality(strengths) from req)=0 or (select strengths from req) <@ c.pstrengths) strength_ok,
    ((select form from req) is null or c.pform is null or (select form from req)=c.pform) form_ok,
    (c.pnorm=(select norm from req)) exact_norm
  from raw_candidates c left join hist h on h.product_id=c.id left join moves m on m.product_id=c.id
), scored as (
 select e.*,least(100,greatest(0,
   e.sim*72 + case when exact_norm then 14 else 0 end
   + case when (select cardinality(strengths) from req)>0 and strength_ok then 7 else 0 end
   + case when (select form from req) is not null and pform is not null and form_ok then 4 else 0 end
   + least(alias_count*4,10) + least(fulfilled_count*1.5,6) + least(ln(1+move_qty)*2.2,10)
   + case when price is not null then 1 else 0 end
   - case when not strength_ok then 45 else 0 end - case when not form_ok then 22 else 0 end
 )) score from enriched e
), ranked as (
 select s.*,row_number() over(order by score desc,sim desc,product_code) rn from scored s
)
select id,product_code,name,price,round(score::numeric,1),round((sim*100)::numeric,1),alias_count,fulfilled_count,move_qty,move_events,last_move,
 strength_ok,form_ok,
 case when not strength_ok then 'تعارض جرعة/تركيز' when not form_ok then 'تعارض شكل دوائي' else null end,
 case when score>=92 and (move_events>0 or alias_count>0 or exact_norm) then 'ثقة عالية جدًا'
      when score>=84 then 'مرشح قوي للمراجعة' when score>=70 then 'مرشح متوسط' else 'ضعيف' end
from ranked where rn<=greatest(1,least(coalesce(p_limit,5),10)) order by rn;
$$;

grant execute on function public.get_customer_request_product_candidates_v2(uuid,integer) to authenticated,service_role;

create or replace function public.auto_link_customer_request_products_v2(p_apply boolean default false,p_branch text default null)
returns jsonb
language plpgsql security definer set search_path=public,pg_catalog as $$
declare v_safe int:=0; v_applied int:=0;
begin
  create temporary table if not exists tmp_customer_request_smart_links(request_id uuid primary key,product_id uuid,score numeric,gap numeric,reason text) on commit drop;
  truncate tmp_customer_request_smart_links;
  insert into tmp_customer_request_smart_links(request_id,product_id,score,gap,reason)
  with reqs as (
    select cr.id from public.customer_requests cr
    where cr.product_id is null and cr.source_system='dawaawael' and cr.source_entity='CustomerOrder'
      and (p_branch is null or p_branch='' or p_branch='all' or cr.branch=p_branch)
  ), candidates as (
    select r.id request_id,c.*,row_number() over(partition by r.id order by c.match_score desc,c.name_similarity desc) rn
    from reqs r cross join lateral public.get_customer_request_product_candidates_v2(r.id,3)c where c.blocked_reason is null
  ), top2 as (
    select request_id,(array_agg(product_id order by rn) filter(where rn=1))[1] best_product,
      max(match_score) filter(where rn=1) best_score,max(match_score) filter(where rn=2) second_score,
      max(name_similarity) filter(where rn=1) best_name,max(alias_confirmations) filter(where rn=1) alias_count,
      max(movement_events_180) filter(where rn=1) move_events,max(fulfilled_history) filter(where rn=1) fulfilled_count
    from candidates group by request_id
  )
  select request_id,best_product,best_score,best_score-coalesce(second_score,0),
    case when move_events>0 then 'مطابقة قوية + حركة صنف موثقة'
         when alias_count>0 then 'اسم سبق ربطه بنفس الكود'
         when fulfilled_count>0 then 'مطابقة قوية + تاريخ طلبات ناجح'
         else 'مطابقة اسم/جرعة شديدة الوضوح' end
  from top2
  where best_product is not null and best_score>=90 and best_name>=78
    and best_score-coalesce(second_score,0)>=8
    and (move_events>0 or alias_count>0 or fulfilled_count>0 or best_score>=96);
  get diagnostics v_safe=row_count;
  if p_apply and v_safe>0 then
    update public.customer_requests cr set product_id=t.product_id
    from tmp_customer_request_smart_links t where cr.id=t.request_id and cr.product_id is null;
    get diagnostics v_applied=row_count;
  end if;
  return jsonb_build_object('safe_suggestions',v_safe,'applied',v_applied,'mode',case when p_apply then 'applied' else 'preview' end,
    'rows',coalesce((select jsonb_agg(jsonb_build_object('request_id',request_id,'product_id',product_id,'score',score,'gap',gap,'reason',reason) order by score desc) from tmp_customer_request_smart_links),'[]'::jsonb));
end;
$$;

grant execute on function public.auto_link_customer_request_products_v2(boolean,text) to authenticated,service_role;

create or replace function public.get_customer_request_product_match_queue_v2(p_branch text default null,p_limit integer default 80)
returns jsonb
language sql stable security definer set search_path=public,pg_catalog as $$
with reqs as (
 select cr.id,cr.source_order_number,cr.medicine_name,cr.quantity,cr.branch,cr.requested_at
 from public.customer_requests cr
 where cr.product_id is null and cr.source_system='dawaawael' and cr.source_entity='CustomerOrder'
   and (p_branch is null or p_branch='' or p_branch='all' or cr.branch=p_branch)
 order by cr.requested_at desc nulls last
 limit greatest(20,least(coalesce(p_limit,80)*3,300))
), expanded as (
 select r.*,c.product_id,c.product_code,c.product_name,c.price,c.match_score,c.name_similarity,c.alias_confirmations,c.fulfilled_history,
        c.movement_qty_180,c.movement_events_180,c.last_movement_date,c.strength_match,c.form_match,c.blocked_reason,c.confidence_label,
        row_number() over(partition by r.id order by c.match_score desc,c.name_similarity desc) rn
 from reqs r left join lateral public.get_customer_request_product_candidates_v2(r.id,3)c on true
), grouped as (
 select id,source_order_number,medicine_name,quantity,branch,requested_at,
   max(match_score) filter(where rn=1) best_score,max(match_score) filter(where rn=2) second_score,
   coalesce(jsonb_agg(jsonb_build_object('product_id',product_id,'product_code',product_code,'product_name',product_name,'price',price,
      'match_score',match_score,'name_similarity',name_similarity,'alias_confirmations',alias_confirmations,'fulfilled_history',fulfilled_history,
      'movement_qty_180',movement_qty_180,'movement_events_180',movement_events_180,'last_movement_date',last_movement_date,
      'strength_match',strength_match,'form_match',form_match,'blocked_reason',blocked_reason,'confidence_label',confidence_label)
      order by rn) filter(where product_id is not null),'[]'::jsonb) candidates
 from expanded group by id,source_order_number,medicine_name,quantity,branch,requested_at
), ranked as (
 select *,coalesce(best_score,0)-coalesce(second_score,0) score_gap from grouped
 order by coalesce(best_score,0) desc,requested_at desc nulls last limit greatest(1,least(coalesce(p_limit,80),150))
)
select jsonb_build_object(
 'total_unlinked',(select count(*) from public.customer_requests cr where cr.product_id is null and cr.source_system='dawaawael' and cr.source_entity='CustomerOrder' and (p_branch is null or p_branch='' or p_branch='all' or cr.branch=p_branch)),
 'movement_evidence_rows',(select count(*) from public.product_movement_evidence),
 'rows',coalesce((select jsonb_agg(jsonb_build_object('id',id,'order_number',source_order_number,'medicine_name',medicine_name,'quantity',quantity,'branch',branch,'requested_at',requested_at,'best_score',best_score,'score_gap',score_gap,'candidates',candidates) order by coalesce(best_score,0) desc,requested_at desc nulls last) from ranked),'[]'::jsonb));
$$;

grant execute on function public.get_customer_request_product_match_queue_v2(text,integer) to authenticated,service_role;

create or replace function public.import_product_movement_evidence_v1(p_rows jsonb,p_source text default 'movement_import')
returns jsonb
language plpgsql security definer set search_path=public,pg_catalog as $$
declare r jsonb; p record; v_imported int:=0; v_rejected int:=0;
begin
  if jsonb_typeof(p_rows)<>'array' then raise exception 'rows_must_be_array'; end if;
  for r in select value from jsonb_array_elements(p_rows) loop
    select * into p from public.products where product_code=trim(coalesce(r->>'product_code',r->>'code','')) limit 1;
    if not found then v_rejected:=v_rejected+1; continue; end if;
    insert into public.product_movement_evidence(product_id,product_code,branch,movement_date,quantity,movement_type,source,source_ref)
    values(p.id,p.product_code,nullif(trim(r->>'branch'),''),coalesce(nullif(r->>'movement_date','')::date,current_date),coalesce(nullif(r->>'quantity','')::numeric,0),coalesce(nullif(trim(r->>'movement_type'),''),'sale'),coalesce(nullif(trim(p_source),''),'movement_import'),nullif(trim(r->>'source_ref'),''));
    v_imported:=v_imported+1;
  end loop;
  return jsonb_build_object('imported',v_imported,'rejected',v_rejected);
end;
$$;

grant execute on function public.import_product_movement_evidence_v1(jsonb,text) to authenticated,service_role;
