-- استيراد بيانات الموردين الحقيقية من Base44 (Supplier entity) — دفعة واحدة،
-- 32 مورد، بعد ما اتأكدنا إن جدول purchase_suppliers فاضي (أول استخدام له).
insert into public.purchase_suppliers (name, payment_type, payment_terms_days, supplier_type, linked_branch, default_purchase_category, default_payment_method, exclude_from_net_purchases) values
('المتحده', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مورد جرد *تعديلات ارصده*', 'آجل', 30, 'external_supplier', null, 'mixed', 'none', true),
('مخزن اتحاد الصيادلة', 'كاش', 30, 'external_supplier', null, 'medicines', 'none', false),
('د حسين', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مورد متنوع (ملاحظات)', 'كاش', 30, 'external_supplier', null, 'mixed', 'none', false),
('اشرف شلبي مستلزمات', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('احمد اسماعيل مستلزمات', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن شاكر اكسسوار', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن طيبة اكسسوار', null, 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن جوي اكسسوار', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('سوفيكو', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('ايفا فارما', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('شحن خارجي', 'كاش', 30, 'external_supplier', null, 'medicines', 'none', false),
('دواء الشامي', 'آجل', 30, 'internal_branch', 'فرع الشامي', 'mixed', 'none', false),
('مخزن الهاشم', 'كاش', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن المحلة', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('صيدليات  111', 'كاش', 30, 'external_supplier', null, 'mixed', 'none', false),
('دواء زكريا', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن الشمس', 'كاش', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن المدينه المنورة اكسسوار', 'آجل', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن هيلثي المنصورة', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن مينا تريد', 'كاش', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن المدينه', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن الحياه اكسسوار', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('دواء شكري', 'آجل', 30, 'internal_branch', 'فرع شكري', 'mixed', 'none', false),
('مخزن كيان اكسسوار', 'آجل', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن المعداوي', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن سونيستا', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('مخزن اورجينال اكسسوار', 'كاش', 30, 'external_supplier', null, 'supplies_accessories', 'none', false),
('مخزن الحياة', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false),
('ابن سينا', 'آجل', 30, 'external_supplier', null, 'none', 'none', false),
('فارما اوفر سيز', 'آجل', 30, 'external_supplier', null, 'medicines', 'none', false);